# Generated by Django 3.0 on 2021-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('dp', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
