# Generated by Django 3.0 on 2021-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210910_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dp',
            field=models.ImageField(default='/media/images/dp.jpg ', upload_to='images'),
        ),
    ]
