# Generated by Django 3.0 on 2021-09-07 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 9, 7, 21, 37, 23, 377082))),
            ],
        ),
    ]
