# Generated by Django 3.0 on 2021-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210909_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
