# Generated by Django 3.0 on 2021-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210909_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privatenotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
