# Generated by Django 3.0 on 2021-09-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_privatenotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='img',
            field=models.ImageField(blank=True, upload_to='attachments'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
